# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import unittest

class TestLoginLogout(unittest.TestCase):
  def setUp(self, method):
    self.driver = webdriver.Chrome(executable_path='C:/Users/Sam Spartan/PycharmProjects/Selenium_proj_2/SIDE_Export/drivers/chromedriver.exe')
    self.vars = {}
  
  def tearDown(self, method):
    self.driver.quit()
  
  def test_loginLogout(self):
    self.driver.get("https://opensource-demo.orangehrmlive.com/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.CSS_SELECTOR, "#divUsername > .form-hint").click()
    self.driver.find_element(By.ID, "txtUsername").send_keys("Admin")
    self.driver.find_element(By.ID, "txtPassword").click()
    self.driver.find_element(By.ID, "txtPassword").send_keys("admin1234")
    self.driver.find_element(By.ID, "btnLogin").click()
    self.driver.find_element(By.ID, "txtUsername").click()
    self.driver.find_element(By.ID, "txtUsername").send_keys("Admin")
    self.driver.find_element(By.ID, "txtPassword").click()
    self.driver.find_element(By.ID, "txtPassword").send_keys("admin123")
    self.driver.find_element(By.ID, "btnLogin").click()
    self.driver.find_element(By.ID, "welcome").click()
    elements = self.driver.find_elements(By.ID, "welcome")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#welcome-menu > ul > li:nth-child(2)")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".inner").click()
    self.driver.find_element(By.ID, "welcome").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
  
